# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./src"
  bin = "tmp/server"
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp"]

[log]
  time = true

[color]
  app = "cyan"
  build = "yellow"
  watcher = "magenta"
