
FROM golang:1.25.1-alpine AS dev

RUN go install github.com/air-verse/air@latest

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY src/ ./src

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
